### ISSUE TITLE
Where does it save the dump?

### ISSUE THREAD

**Issue by HoppersPS4** [obhq/kernel-dumper#1]
hello, 
cool payload. but hmmmmmmm where does it save the kernel?

ty

**Comment by ultimaweapon** [comment]
It is not working yet. All the code currently does is just read and write `cr0` register to see if the code is working inside the PS4 kernel.

**Comment by iy26adchak** [comment]
so its not a dumper, its just a reader for now, please correct the tittle

**Comment by ultimaweapon** [comment]
Updated.

**Comment by zauceee** [comment]
To get the actual dump, couldn't you read it, save it, and send it back to the PC?

**Comment by ultimaweapon** [comment]
Something like that. It's not hard if you take a look on PPPwn stage 2 source and understand how it works. All you need to dump the kernel already there.

**Comment by ultimaweapon** [comment]
See the README for the instructions.
